### ISSUE TITLE
KeyError when running query-bids

### ISSUE THREAD

**Issue by jeffrey-phillips** [PennBBL/bids-on-flywheel#1]
Hi folks--I ran into the error below when trying to extract a csv of project info using query-bids. I'm using Python 2.7.15rc1 on Ubuntu 18.04.02. The output below says the 5 files in my test project directory have no BIDS information, although I did run the BIDS curation gear on them. Not sure whether this is a software issue or an issue with the project data themselves--I'm happy to provide additional info if helpful. 

Thanks,

Jeff

$ query-bids -proj BOLD -out BOLD.csv
Connecting to flywheel server...
Querying server...
Processing acquisitions...
100%|██████████| 1/1 [00:00<00:00,  5.53it/s]
Extracting BIDS and MR Classifier information...
100%|██████████| 5/5 [00:00<00:00, 11.79it/s]
Tidying and returning the results...
0 acquisitions could not be processed.
5 acquisitions do not have BIDS information yet.
Traceback (most recent call last):
  File "/home/jeff/.local/bin/query-bids", line 11, in <module>
    sys.exit(main())
  File "/home/jeff/.local/lib/python2.7/site-packages/flywheel_bids_tools/query_bids.py", line 265, in main
    query_result.loc[:, drop_downs] = query_result.loc[:, drop_downs].applymap(unlist_item)
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 189, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 167, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 248, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/home/jeff/.local/lib/python2.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['classification_Features'] not in index"

**Comment by TinasheMTapera** [comment]
Hey Jeff, it looks like the key error is coming from the MR classifier info not being present. Has your project had any MR classification run on it? You can usually see this in the middle column of an acquisition view:
<img width="1218" alt="screenshot" src="https://user-images.githubusercontent.com/15770644/58044270-5ad1c900-7b0d-11e9-81b7-352af9a6d3a3.png">

**Comment by jeffrey-phillips** [comment]
Hey Tinashe,

Thanks for getting back to me. Yes, I did run dicom-mr-classifier v0.8.2 on the data, and there are values in the classification field. Could the problem be due to the B0 scan, which the classifier failed on?

Thanks,

Jeff

![BIDS](https://user-images.githubusercontent.com/5494290/58044622-36c2b780-7b0e-11e9-8fa7-4f56ef0089ff.png)

**Comment by TinasheMTapera** [comment]
Thanks for that info Jeff.

[I think I can see where the issue lies](https://github.com/PennBBL/bids-on-flywheel/blob/554d7d21452e0c41647aec8193f6d655d7a2eaf0/flywheel_bids_tools/query_bids.py#L271), and will try to amend it in the next few hours. The B0 scan should not be a problem. I'll reach out to you when I've given this a crack.

**Comment by jeffrey-phillips** [comment]
Thanks a ton! Sorry, Python novice here, or I would have suggested a fix
myself.

**Comment by TinasheMTapera** [comment]
@jeffrey-phillips thanks for your patience with this. Please use Github's `clone this repository` function to get the latest version of this tool.

The issue was being caused by a module that "unlisted" columns that came from drop-down fields (e.g., a field in Flywheel may have values A, B, and C, and thus when exported the cell looks like "[A, B, C]").

I've removed this functionality as supporting it causes headaches further down the line, but be warned that until we reimplement it more robustly, **it's required that users not remove the list brackets from their CSVs**.

Hope this helps!
